export const SET_FETCHED_DATA = 'SET_FETCHED_DATA';
export const TOGGLE_TICKET_DETAIL_MODAL = 'TOGGLE_TICKET_DETAIL_MODAL';
export const TOGGLE_FETCHING_TICKET_DETAIL_ICON = 'TOGGLE_FETCHING_TICKET_DETAIL_ICON';