export const POPULATE_DATA = 'POPULATE_DATA';
export const POPULATE_DATA_TICKETS = "POPULATE_DATA_TICKETS ";
export const SET_SELECTED_TICKET_ID = "SET_SELECTED_TICKET_ID";
export const SET_SELECTED_NOTIF_ID = "SET_SELECTED_NOTIF_ID";
export const TOGGLE_DISMISS_CONFIRMATION_PROMP = "TOGGLE_DISMISS_CONFIRMATION_PROMP";
export const UPDATE_NOTIF_DATA = "UPDATE_NOTIF_DATA";