export const SET_SELECTED_TICKET_ID = "SET_SELECTED_TICKET_ID";
export const SET_SELECTED_NOTIF_ID = "SET_SELECTED_NOTIF_ID";
export const TOGGLE_DISMISS_CONFIRMATION_PROMP = "TOGGLE_DISMISS_CONFIRMATION_PROMP";