export const SET_TICKET_UPDATE_LOGS_DATA = 'SET_TICKET_UPDATE_LOGS_DATA';
export const TOGGLE_TICKET_UPDATE_LOGS_MODAL = 'TOGGLE_TICKET_UPDATE_LOGS_MODAL';
export const TOGGLE_FETCHING_DATA_ICON = 'TOGGLE_FETCHING_DATA_ICON';